version: "3.8"
services:
  bitcoind:
    image: "ruimarinho/bitcoin-core:0.20"
    command:
      - -testnet
      - -server
      - -maxuploadtarget=200
      - -blocksonly
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcuser=rpcuser
      - -rpcpassword=rpcpassword
      - -fallbackfee=0.0002
    ports:
      - "18332:18332"
    volumes:
      - ./cache:/home/bitcoin/.bitcoin/testnet3
    restart: unless-stopped
  staked_relayer:
    image: "registry.gitlab.com/interlay/polkabtc-clients/staked-relayer:0-7-5"
    command:
      - staked-relayer
      - --bitcoin-rpc-url
      - "http://bitcoind:18332"
      - --bitcoin-rpc-user
      - rpcuser
      - --bitcoin-rpc-pass
      - rpcpassword
      - --keyfile
      - /keyfile.json
      - --keyname
      - polkabtcrelayer
      - --auto-fund-with-faucet-url
      - "https://beta.polkabtc.io/api/faucet"
      - --btc-parachain-url
      - "wss://beta.polkabtc.io/api/parachain"
    environment:
      RUST_LOG: info
    volumes:
      - type: bind
        source: ./keyfile.json
        target: /keyfile.json
    restart: unless-stopped
